foam.CLASS({
  package: 'com.foamdev.cook',
  name: 'IngredientAmount',

  sections: [
    { name: 'main',  title: 'Ingredient',  order: 1 },
    { name: 'other', title: 'Alternative', order: 2 }
  ],

  tableColumns: [ 'id', 'amount', 'unit', 'ingredient' ],

  properties: [
    {
      class: 'Long',
      name: 'id',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      class: 'Float',
      name: 'amount',
      section: 'main',
      gridColumns: 4,
      // 'ingredient' is required via the relationship's targetProperty, so its
      // message shows under the ingredient field. Here we only guard the amount.
      validateObj: function(amount) {
        if ( ! ( amount > 0 ) ) return 'Enter an amount greater than 0.';
      }
    },
    {
      class: 'Enum',
      of: 'com.foamdev.cook.Unit',
      name: 'unit',
      section: 'main',
      gridColumns: 4
    },
    {
      // Optional substitute — a reference to another IngredientAmount (stored by
      // id). The custom picker lets you select an existing one or create a new
      // substitute in place, and keeps the Alternative section non-empty so its
      // tab always renders.
      class: 'Reference',
      of: 'com.foamdev.cook.IngredientAmount',
      name: 'alternative',
      targetDAOKey: 'ingredientAmountDAO',
      value: 0,
      section: 'other',
      view: { class: 'com.foamdev.cook.AlternativePickerView' }
    },
    {
      // In-memory, human-readable label (ingredient name + amount + unit). Transient —
      // never persisted or sent over the wire — because it derives from the *referenced*
      // Ingredient. It's a self-populating expression: resolving the ingredient is async,
      // so we return '' immediately and set the real value once toSummary() resolves (the
      // same pattern comics DetailView uses for viewTitle). Views can then bind summary$
      // for a reactive label, and a client-side (in-memory) DAO can be searched by SUMMARY
      // — which the server can't do, since the field is transient and derived.
      class: 'String',
      name: 'summary',
      transient: true,
      hidden: true,
      expression: function(ingredient, amount, unit) {
        // No ingredient yet -> nothing to summarize (and toSummary would throw on the
        // null reference). 'summary' isn't one of this expression's dependencies, so
        // setting it in the callback doesn't re-trigger the expression.
        if ( ! ingredient ) return '';
        var self = this;
        this.toSummary().then(v => { self.summary = v; });
        return '';
      }
    }
  ],

  methods: [
    {
      name: 'toSummary',
      type: 'String',
      code: async function() {
        // The ingredient is a reference, so we need to await its resolution to get its name.
        // The ingredient$find method is generated by the Reference property, and returns a promise that resolves to the referenced object.
        let ingredient = await this.ingredient$find;
        return ingredient.name + " " + this.amount + ' ' + this.unit?.label;
      },
      // Nice to have for optimization purposes: with a Java implementation the
      // summary can be generated on the server, reducing bandwidth (no need to
      // ship the referenced Ingredient to the client just to build the summary).
      javaCode: `
        Ingredient ingredient = findIngredient(foam.lang.XLocator.get());
        return ingredient.getName() + " " + getAmount() + " " + ( getUnit() != null ? getUnit().getLabel() : "" );
      `
    }
  ]
});
