foam.CLASS({
  package: 'com.foamdev.cook',
  name: 'IngredientAmount',

  sections: [
    { name: 'main',  title: 'Ingredient',  order: 1 },
    { name: 'other', title: 'Alternative', order: 2 }
  ],

  tableColumns: [ 'id', 'amount', 'unit', 'ingredient' ],

  properties: [
    {
      class: 'Long',
      name: 'id',
      createVisibility: 'HIDDEN',
      updateVisibility: 'RO'
    },
    {
      class: 'Float',
      name: 'amount',
      section: 'main',
      gridColumns: 4,
      // 'ingredient' is required via the relationship's targetProperty, so its
      // message shows under the ingredient field. Here we only guard the amount.
      validateObj: function(amount) {
        if ( ! ( amount > 0 ) ) return 'Enter an amount greater than 0.';
      }
    },
    {
      class: 'Enum',
      of: 'com.foamdev.cook.Unit',
      name: 'unit',
      section: 'main',
      gridColumns: 4
    },
    {
      // Optional substitute — a reference to another IngredientAmount (stored by
      // id). The custom picker lets you select an existing one or create a new
      // substitute in place, and keeps the Alternative section non-empty so its
      // tab always renders.
      class: 'Reference',
      of: 'com.foamdev.cook.IngredientAmount',
      name: 'alternative',
      targetDAOKey: 'ingredientAmountDAO',
      value: 0,
      section: 'other',
      view: { class: 'com.foamdev.cook.AlternativePickerView' }
    },
    {
      // In-memory, human-readable label (ingredient + amount + unit). Transient, so
      // it is never persisted or sent over the wire — it can't be, since it derives
      // from the *referenced* Ingredient. Pickers populate it client-side (from
      // toSummary) so their search can match on the readable summary rather than only
      // on IngredientAmount's own stored fields (which don't include the name).
      class: 'String',
      name: 'summary',
      transient: true,
      hidden: true
    }
  ],

  methods: [
    {
      name: 'toSummary',
      type: 'String',
      code: async function() {
        // The ingredient is a reference, so we need to await its resolution to get its name.
        // The ingredient$find method is generated by the Reference property, and returns a promise that resolves to the referenced object.
        let ingredient = await this.ingredient$find;
        return ingredient.name + " " + this.amount + ' ' + this.unit?.label;
      },
      // Nice to have for optimization purposes: with a Java implementation the
      // summary can be generated on the server, reducing bandwidth (no need to
      // ship the referenced Ingredient to the client just to build the summary).
      javaCode: `
        Ingredient ingredient = findIngredient(foam.lang.XLocator.get());
        return ingredient.getName() + " " + getAmount() + " " + ( getUnit() != null ? getUnit().getLabel() : "" );
      `
    }
  ]
});
